name: deploy-dev
on:
  workflow_dispatch:
    inputs:
      deploy-environment:
        description: 'Choose an environment to deploy to'
        required: true
        type: choice
        options:
          - develop
          - production

env:
  develop: 'public_html/dev'
  production: 'public_html'

jobs:
  job-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo ${{ env.inputs.deploy-environment }}
      # - name: Get code
      #   uses: actions/checkout@v4
      # - name: Install node 20
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: 20
      # - name: Install dependencies
      #   run: npm ci
      # - name: Create build
      #   run: npm run build
      # - name: Sync files
      #   uses: kevinpainchaud/simple-ftp-deploy-action@v1.2.1
      #   with:
      #     ftp_host: ${{ secrets.FTP_SERVER }}
      #     ftp_username: ${{ secrets.FTP_USER }}
      #     ftp_password: ${{ secrets.FTP_PASSWORD }}
      #     local_source_dir: 'out'
      #     dist_target_dir: 'public_html/dev'
