name: deploy-dry
on: workflow_dispatch
jobs:
  job-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Sync files
        uses: sebastianpopp/ftp-action@releases/v2
        with:
          host: ${{ secrets.FTP_SERVER }}
          user: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          remoteDir: public_html
